Repository openshift/rbac-permissions-operator, pull requests merged in 2019-07, with the labels that each got.

#2 added initial crd with apiVersion and kind
  deploy/crds/managed_v1alpha1_grouppermission_cr.yaml
  deploy/crds/managed_v1alpha1_grouppermission_crd.yaml
  deploy/role.yaml
  pkg/apis/addtoscheme_managed_v1alpha1.go
  pkg/apis/managed/v1alpha1/doc.go
  pkg/apis/managed/v1alpha1/grouppermission_types.go
  pkg/apis/managed/v1alpha1/register.go
  pkg/apis/managed/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/managed/v1alpha1/zz_generated.openapi.go
Labels: size/L

#3 added CRD spec and status as go structs
  pkg/apis/managed/v1alpha1/grouppermission_types.go
  pkg/apis/managed/v1alpha1/zz_generated.deepcopy.go
Labels: size/L

#4 generate openapi to update yaml file
  deploy/crds/managed_v1alpha1_grouppermission_crd.yaml
  pkg/apis/managed/v1alpha1/zz_generated.openapi.go
Labels: size/L

#5 added template for controller and needed functions for dedicated admins
  pkg/apis/managed/v1alpha1/grouppermission_types.go
  pkg/controller/add_grouppermission.go
  pkg/controller/grouppermission/grouppermission_controller.go
  pkg/dedicatedadmin/dedicatedadmin.go
  pkg/dedicatedadmin/dedicatedadmin_test.go
  pkg/dedicatedadmin/project/resources.go
  pkg/utility/grouppermissions.go
  pkg/utility/grouppermissions_test.go
  pkg/utility/namespaces.go
  pkg/utility/namespaces_test.go
Labels: size/XL

#6 add makefile
  Makefile
Labels: size/S

#7 Fix paths to point to openshift repo, make functions
  Makefile
  cmd/manager/main.go
  go.mod
  pkg/apis/addtoscheme_managed_v1alpha1.go
  pkg/apis/managed/v1alpha1/zz_generated.openapi.go
  pkg/controller/add_grouppermission.go
  pkg/controller/grouppermission/grouppermission_controller.go
  pkg/utility/grouppermissions.go
  pkg/utility/grouppermissions_test.go
  project.mk
  standard.mk
Labels: size/L

#9 Fix Docker and make builds
  build/Dockerfile
  config/config.go
  go.mod
  go.sum
  pkg/apis/managed/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/managed/v1alpha1/zz_generated.openapi.go
  vendor/github.com/openshift/dedicated-admin-operator/LICENSE
  vendor/github.com/openshift/dedicated-admin-operator/config/config.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil/controllerutil.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/event/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/event/event.go
  vendor/sigs.k8s.io/controller-runtime/pkg/handler/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/handler/enqueue.go
  vendor/sigs.k8s.io/controller-runtime/pkg/handler/enqueue_mapped.go
  vendor/sigs.k8s.io/controller-runtime/pkg/handler/enqueue_owner.go
  vendor/sigs.k8s.io/controller-runtime/pkg/handler/eventhandler.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/metrics/metrics.go
  vendor/sigs.k8s.io/controller-runtime/pkg/predicate/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/predicate/predicate.go
  vendor/sigs.k8s.io/controller-runtime/pkg/reconcile/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/reconcile/reconcile.go
  vendor/sigs.k8s.io/controller-runtime/pkg/runtime/scheme/scheme.go
  vendor/sigs.k8s.io/controller-runtime/pkg/source/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/source/internal/eventsource.go
  vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go
Labels: lgtm, size/XXL

#10 Add owners file
  OWNERS
Labels: lgtm, size/S

#8 initial controller logic
  go.mod
  pkg/apis/managed/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/managed/v1alpha1/zz_generated.openapi.go
  pkg/controller/grouppermission/grouppermission_controller.go
Labels: approved, lgtm, size/L

#11 SREP-1754: Prefer native types
  deploy/crds/managed_v1alpha1_grouppermission_crd.yaml
  pkg/apis/managed/v1alpha1/grouppermission_types.go
  pkg/apis/managed/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/managed/v1alpha1/zz_generated.openapi.go
  pkg/controller/grouppermission/grouppermission_controller.go
  pkg/utility/grouppermissions.go
  pkg/utility/grouppermissions_test.go
Labels: approved, lgtm, size/M
