Repository openshift/rbac-permissions-operator, pull requests merged in 2019-08, with the labels that each got.

#13 fix populateClusterRoleBindingNames bug
  pkg/controller/grouppermission/grouppermission_controller.go
Labels: approved, lgtm, size/S

#14 fix clusterRoleList and clusterRoleBindingList
  pkg/controller/grouppermission/grouppermission_controller.go
Labels: approved, lgtm, size/XS

#12 unit tests implementation
  pkg/controller/grouppermission/grouppermission_controller.go
  pkg/controller/grouppermission/grouppermission_controller_test.go
  vendor/github.com/evanphx/json-patch/.travis.yml
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/k8s.io/client-go/testing/actions.go
  vendor/k8s.io/client-go/testing/fake.go
  vendor/k8s.io/client-go/testing/fixture.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
Labels: approved, lgtm, size/XXL

#15 SREP-1549: Export metrics for GroupPermissions
  .gitignore
  build/Dockerfile
  cmd/manager/main.go
  go.mod
  go.sum
  pkg/controller/grouppermission/grouppermission_controller.go
  pkg/localmetrics/localmetrics.go
  pkg/localmetrics/localmetrics_test.go
  standard.mk
Labels: approved, do-not-merge/hold, lgtm, size/L
