Repository openshift/rbac-permissions-operator, pull requests merged in 2019-11, with the labels that each got.

#34 Add and edit hack folder
  config/templates/rbac-permissions-operator-csv-template.yaml
  hack/app_sre_build_deploy.sh
  hack/app_sre_create_image_catalog.sh
  hack/app_sre_pr_check.sh
  hack/generate-operator-bundle.py
  hack/olm-registry/olm-artifacts-template.yaml
  hack/validate_yaml.py
Labels: approved, lgtm, size/L

#35 Update log
  pkg/controller/namespace/namespace_controller.go
  pkg/controller/subjectpermission/subjectpermission_controller.go
Labels: approved, lgtm, size/XS

#39 Bind rbac ServiceAccount to cluster-admin
  deploy/cluster_role_binding.yaml
Labels: approved, lgtm, size/XS

#37 Add selectorsyncsets
  deploy/prom-k8s-role.yaml
  deploy/prom-k8s-rolebinding.yaml
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm, size/L

#40 Replace quay image tag for operator.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#41 Remove operator-sdk generate from Makefile
  Makefile
Labels: approved, lgtm, size/XS

#42 Fix OPERATOR_IMAGE_URI
  standard.mk
Labels: approved, lgtm, size/XS

#43 Fix generate operator bundle script
  hack/generate-operator-bundle.py
Labels: approved, lgtm, size/M
